name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show directory
      run: ls
    - name: Go to root directory
      run: cd ./tlc-lisp-interpreter
    - name: Show directory (again)
      run: ls
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
